function previewFile(FilePathFilePath){
    var fileData = new FileReader();
    fileData.onload = (function() {
        document.getElementById('preview').src = fileData.result;
    });
    fileData.readAsDataURL(FilePathFilePath.files[0]);
}

function toggleLanguage(language) {
    
    const text = {
        japanese: {
            "text-1": "私たちは、開発から導入までの一貫したサポートを提供するワンストップソリューションを提供しています。お客様のお困りごとやご要望をしっかりとお聞きし、それに基づいて最適な提案を行います。もし、初めてシステム導入をお考えで、「どこから始めればよいか分からない」とお悩みの方も、豊富な実績を持つスタッフが、導入プロセスをしっかりとサポートいたしますので、ご安心ください。",
            "paragraph1":"お客様のビジネスニーズや業務課題を深く理解し、業務に最適なオーダーメイドのソフトウェア開発を提供しています。お客様の業種やビジネス規模に合わせて、最適なソリューションを設計・開発し、業務の効率化やプロセスの自動化を支援します。これにより、業務の無駄を削減し、作業時間の短縮やヒューマンエラーの削減など、効率的な運営を実現します。",
            "paragraph2":"私たちは、単なるシステム提供にとどまらず、お客様の成長に寄与するために、長期的なパートナーとしてサポートいたします。常に変化する市場環境やお客様のニーズに応じて、柔軟に対応し、進化するビジネスの要件に最適な技術を提供し続けます。",
            "text-2":"私たちは、企業やブランドの魅力を最大限に引き出すためのホームページと広告の設計・制作を手掛けています。デザイン性と機能性を巧妙に融合させ、視覚的なインパクトと優れたユーザー体験を提供。私たちのクリエイティブな提案は、ただのデジタルデザインにとどまらず、ブランドのメッセージを鮮やかに伝える力強い表現となり、ユーザーの心を掴みます。最先端の技術と独自の視点で、企業の成長を加速させるデジタル体験を創出します。あなたのブランドを次のステージへと導く、唯一無二のパートナーとなります。",
            "paragraph3":"私たちは、お客様の課題を徹底的に理解し、業務効率化や生産性向上を実現する業務代行サービスを提供しています。経験豊富な専門スタッフと柔軟な体制で、あらゆる業務に対応。企業の成長を加速させるため、単なるサポートにとどまらず、貴社の戦略的パートナーとして信頼をいただいています。効率化を超えた革新的なアプローチで、業務の負担を軽減し、最前線で活躍できる体制を構築。これにより、企業が持つ潜在能力を最大限に引き出し、 持続可能な成長を支援します。私たちと共に、未来のビジネスシーンに勝ち抜くための強力な基盤を築きましょう。",
            "text-3":"当社では、事務代行業務の一環として、業務フローやマニュアルの作成を行います。これにより、サービス利用中はもちろん、サービス終了後もお客様が円滑に業務を引き継げる体制を整備します。また、定期的なノウハウ共有や、必要に応じた研修サポートも実施し、社内にスキルを蓄積できるよう支援いたします。",
            "text-4":"日々の業務報告書に加え、週次や月次での定例報告ミーティングを通じて、業務内容を詳細にご報告します。このプロセスにより、業務の見える化を実現し、お客様が効率性を常に確認できるようにします。また、ヒアリングを通じてお客様の要望を反映し、最適なサービス提供を心がけています。",
            "text-5":"当社は、プライバシーマークおよびISMS（情報セキュリティマネジメントシステム）認証を取得しており、情報管理体制の信頼性を保証しています。さらに、業務を行う設備は最新のセキュリティ対策を導入し、機密情報の保護に万全を期しています。契約時には、秘密保持契約（NDA）を締結し、安心してご利用いただける環境を提供します。",
            "text-6":"近年、ビジネスモデル変革や新規事業創出においてはデータの収集・蓄積・利活用が重要になっています。「収集」ではいかに顧客データやIoTデータを集めるか、「蓄積」では元データをいかに利用しやすいように加工・処理・保管するか、「利活用」では機会学習やBIツールを使用していかに分析するかがポイントです。したがって、ビジネスモデル変革や新規事業創出はDXと切っても切り離せない関係になりつつあると言えます。業務系ソリューション事業では流通業、金融業、サービス業、製造業、ネットビジネス、社会インフラ、教育、文教、医療、公共機関など幅広いクライアントに対しコンサルティング・開発・システム構築・サポートを行っているほか、テクノロジーを活かしたモノづくりも得意な企業です。流通業、金融業、サービス業、製造業、ネットビジネス、社会インフラ、教育、文教、医療、公共機関など、あらゆるニーズに、「お客様にとってのベストは何か」を徹底的に追求し、コンサルティング、開発、システム構築からサポートまで充実した体制でトータルソリューションをご提供いたします。",
            "text-7":"業務系ソリューション事業では流通業、金融業、サービス業、製造業、ネットビジネス、社会インフラ、教育、文教、医療、公共機関など幅広いクライアントに対しコンサルティング・開発・システム構築・サポートを行っているほか、テクノロジーを活かしたモノづくりも得意な企業です。流通業、金融業、サービス業、製造業、ネットビジネス、社会インフラ、教育、文教、医療、公共機関など、あらゆるニーズに、「お客様にとってのベストは何か」を徹底的に追求し、コンサルティング、開発、システム構築からサポートまで充実した体制でトータルソリューションをご提供いたします。",
            "text-8":"設計・開発の効率化、生産性向上は製造業を中心に関心を集めているテーマです。このテーマにおけるDXの目標は、熟練者が意識せずできていることを、非熟練者でもできるようにすることと言えます。またその先には、誰でもできるようになった業務はAIに代替させることを見据えることも可能です。",
            "text-9": "人材育成 / 教育の領域でも企業の競争力強化のためのDX推進が求められています。その主要な狙いはデータの可視化による人材マネジメントの高度化です。従業員に関する膨大なデータ（スキル・特性・経歴など）を一元管理することで精度の高い適材適所の人員配置ができれば、企業経営にとっても従業員のモチベーションにとっても効果的な人材マネジメントが実現します。",
            "text-10": "製造業ではエンジニアリングチェーン（開発－製品設計－工程設計－生産などの連鎖）とサプライチェーン（受発注－生産管理－生産－流通・販売－アフターサービスなどの連鎖）において幅広くDXが推進されています。",
            "text-11": "医療 / 介護業界では医療従事者不足が深刻化しています。不規則な労働環境や責任の重さなどに起因するなり手不足、そして高齢化の進行による需要拡大が要因です。DXはこのような医療 / 介護業界の課題解決手段として注目されています。具体的には医療機器の高度化、医療情報のネットワーク化、遠隔診療、IoTを活用した見守りなどが挙げられます。日本政府も「医療DX令和ビジョン2030」を制定し、国民がより良質な医療やケアを受けられる社会や生活の形を変えることを目指しています。",
            "text-12": "さらなるインバウンド需要を取り込み観光立国を目指す日本では、観光業界のDXも推進されています。国土交通省は、予約・決済が可能な地域サイトの構築、情報のレコメンド、顧客予約管理システム（PMS）の導入等による業務効率化及びサービスの高付加価値化、旅行者の旅マエ・旅ナカ・旅アトの予約・移動・宿泊・購買データ等を用いたマーケティング及び観光地経営の戦略策定等の取り組みをDXで推進することを掲げています。",
            "text-13": "教育業界のDXも文部科学省主導で推進されています。DXにより期待される変化としては、学習データを活用した指導の個別最適化、リモート授業などによる場所を選ばない学習環境構築、教員の事務作業府赤軽減などがあるでしょう。一方で情報システム部門などのIT系の部門をもたない教育現場では、DX推進に関する知識不足・経験不足が問題になりやすく、いかに外部リソースを活用するかが課題になっています。",
            "text-14": "小売業界は、システムの老朽化、慢性的な人材不足、経営判断に必要なデータの不足などの課題に直面しており、課題解決の手段としてDXが着目されています。システムの老朽化に対してはクラウド化や最新システム導入、人材不足に対してはAI・RPAの導入、データ不足に対してはECによるデータ収集などが考えられます。"
        },
        english: {
            "text-1": "We provide a one-stop solution offering comprehensive support from development to implementation. We carefully listen to our customers' concerns and requests and make the most suitable proposals based on them. For those who are considering system implementation for the first time and are unsure where to start, our experienced staff, with a wealth of proven results, will provide full support throughout the implementation process, so you can proceed with confidence.",
            "paragraph1":"We deeply understand our clients' business needs and operational challenges, and provide tailored software development solutions that are best suited to their operations. Based on the client's industry and business scale, we design and develop optimal solutions to streamline operations and automate processes. This helps reduce inefficiencies, shorten working hours, and minimize human errors, achieving more efficient operations.",
            "paragraph2":"We do not merely provide systems; we support our customers as long-term partners to contribute to their growth. We flexibly adapt to ever-changing market environments and customer needs, continuously delivering the best technologies to meet evolving business requirements.",
            "text-2":"We specialize in designing and creating websites and advertisements that maximize the appeal of businesses and brands. By skillfully blending design and functionality, we provide visual impact and an exceptional user experience. Our creative proposals go beyond just digital design—they become powerful expressions that vividly convey the brand's message, capturing the hearts of users. With cutting-edge technology and a unique perspective, we create digital experiences that accelerate business growth. We will be the one-of-a-kind partner that takes your brand to the next stage.",
            "paragraph3":"We provide business outsourcing services that thoroughly understand our clients' challenges and help achieve operational efficiency and productivity improvements. With experienced specialists and a flexible structure, we handle all kinds of tasks. To accelerate the growth of businesses, we are trusted not only as a support provider but also as a strategic partner. Through innovative approaches that go beyond simple efficiency, we alleviate the burden of operations and build a structure that allows businesses to excel at the forefront. This helps unlock the full potential of companies and supports sustainable growth. Let's build a strong foundation together to succeed in the future business world.",
            "text-3":"We create workflows and manuals as part of our administrative outsourcing services, ensuring smooth transitions for clients during and after the service. We also provide ongoing knowledge sharing and training support to help clients build skills within their organization.",
            "text-4":"We provide detailed updates through daily reports and regular weekly and monthly meetings, ensuring transparency and allowing customers to monitor efficiency. By listening to customer feedback, we aim to incorporate their requests and deliver optimal service.",
            "text-5":"Our company holds Privacy Mark and ISMS certifications, ensuring reliable information management. We also use the latest security measures to protect confidential information and sign NDAs for a secure environment.",
            "text-6":"In recent years, the collection, accumulation, and utilization of data have become crucial in business model transformation and the creation of new businesses. In the 'collection' phase, the focus is on how to gather customer data and IoT data. In the 'accumulation' phase, it is important to process, organize, and store the raw data in a way that makes it easy to use. In the 'utilization' phase, the key is how to analyze the data using machine learning and BI tools. Therefore, business model transformation and the creation of new businesses are increasingly inseparable from digital transformation (DX).",
            "text-7":"Our business solutions division provides consulting, development, system construction, and support for a wide range of clients, including those in distribution, finance, services, manufacturing, online business, social infrastructure, education, academia, healthcare, and public institutions. Additionally, we excel in utilizing technology for manufacturing.We are committed to thoroughly pursuing 'what is best for our customers' across various industries, including distribution, finance, services, manufacturing, online business, social infrastructure, education, academia, healthcare, and public institutions. With a comprehensive system in place, we offer total solutions from consulting and development to system construction and support.",
            "text-8":"The theme of improving efficiency in design and development and enhancing productivity is gaining attention, especially in the manufacturing industry. The goal of DX (Digital Transformation) in this context is to enable non-experienced workers to perform tasks that skilled workers can do without thinking. Furthermore, looking ahead, tasks that have become accessible to anyone can eventually be replaced by AI.",
            "text-9": "In the field of human resource development and education, the promotion of DX (Digital Transformation) for strengthening corporate competitiveness is also being sought. The main goal is to enhance human resource management through data visualization. By centrally managing vast amounts of data about employees (such as skills, characteristics, and career history), companies can achieve accurate and effective personnel placement, which in turn leads to better human resource management, benefiting both corporate management and employee motivation.",
            "text-10": "In the manufacturing industry, DX (Digital Transformation) is being promoted widely across the engineering chain (development - product design - process design - production, etc.) and the supply chain (order receipt and dispatch - production management - production - distribution and sales - after-sales service, etc.).",
            "text-11": "In the healthcare and nursing care industries, the shortage of medical professionals has become a serious issue. This is due to factors such as irregular working conditions, the heavy responsibility of the job, and the expansion of demand caused by the aging population. DX (Digital Transformation) is gaining attention as a solution to these challenges in the healthcare and nursing care sectors. Specifically, this includes the advancement of medical devices, the networking of medical information, telemedicine, and the use of IoT for monitoring. The Japanese government has also established the 'Medical DX Reiwa Vision 2030' with the aim of transforming society and life to enable citizens to receive better quality healthcare and care.",
            "text-12": "In Japan, which aims to become a tourism-oriented country by capturing further inbound demand, DX in the tourism industry is also being promoted. The Ministry of Land, Infrastructure, Transport and Tourism is advancing DX initiatives to improve business efficiency and enhance service value by building regional websites that allow reservations and payments, recommending information, and introducing customer reservation management systems (PMS). They are also focusing on marketing and the development of tourism strategies using data from travelers' pre-trip, during-trip, and post-trip reservations, movements, accommodations, purchases, and other activities.",
            "text-13": "DX in the education industry is also being promoted under the leadership of the Ministry of Education, Culture, Sports, Science and Technology. Expected changes due to DX include the individual optimization of instruction using learning data, the creation of learning environments that are not limited by location through remote classes, and the reduction of administrative tasks for teachers. On the other hand, in educational settings that do not have IT departments such as information systems divisions, the lack of knowledge and experience regarding the promotion of DX can become problematic. The challenge is how to effectively utilize external resources.",
            "text-14":"The retail industry is facing challenges such as outdated systems, chronic labor shortages, and a lack of data necessary for management decisions. DX is being focused on as a solution to these problems. To address outdated systems, cloud adoption and the introduction of the latest systems are being considered. For labor shortages, the introduction of AI and RPA is being explored, while for data shortages, data collection through e-commerce is being considered.",
        },
        chinese: {
            "text-1": "我们提供从开发到实施的全方位支持的一站式解决方案。我们会认真听取客户的困扰和需求，并根据这些需求提出最合适的建议。如果您是第一次考虑实施系统，且不知道从哪里开始，我们经验丰富的团队将全程支持实施过程，让您放心进行。",
            "paragraph1":"我们深入理解客户的业务需求和运营挑战，提供最适合其业务的定制软件开发。根据客户的行业和业务规模，我们设计和开发最佳解决方案，支持业务的效率提升和流程自动化。通过这些措施，帮助减少运营中的浪费，缩短工作时间并减少人为错误，从而实现高效的运营。",
            "paragraph2":"我们不仅仅提供系统，而是作为长期合作伙伴支持客户的成长。我们灵活应对不断变化的市场环境和客户需求，持续提供最适合不断发展的业务需求的技术。",
            "text-2":"我们专注于设计和制作网站和广告，最大限度地发挥企业和品牌的魅力。巧妙地融合设计性和功能性，提供视觉冲击力和卓越的用户体验。我们的创意提案不仅仅是数字设计，更是能够生动传达品牌信息的有力表达，深深打动用户的心。通过最前沿的技术和独特的视角，我们创造加速企业增长的数字体验。我们将成为您品牌走向下一个阶段的独一无二的伙伴。",
            "paragraph3":"我们提供深入理解客户挑战的业务外包服务，帮助实现业务效率化和生产力提升。凭借经验丰富的专业团队和灵活的架构，我们能够应对各种业务需求。为了加速企业的增长，我们不仅提供支持，还作为贵公司的战略合作伙伴赢得了信赖。通过超越效率化的创新方法，减轻业务负担，构建能够在前线发挥作用的体制。这样，我们帮助企业充分发掘其潜力，支持可持续发展。让我们一起打造强大的基础，为未来的商业竞争打下坚实的根基。",
            "text-3":"我们作为事务外包服务的一部分，提供业务流程和手册的编写。通过这一措施，我们确保客户不仅在服务期间，而且在服务结束后，也能够顺利地接手业务。此外，我们还定期进行知识分享，并根据需要提供培训支持，帮助客户在公司内部积累技能。",
            "text-4":"除了日常的业务报告，我们还通过每周和每月的定期报告会议，详细汇报业务内容。通过这一过程，我们实现了业务的可视化，让客户能够随时确认工作效率。此外，通过倾听客户需求，我们致力于反映客户的要求，提供最优化的服务。",
            "text-5":"本公司已获得隐私标志和ISMS（信息安全管理体系）认证,确保信息管理体系的可靠性。此外,我们的工作设施已采用最新的安全措施,确保机密信息的保护。在签订合同时,我们将签署保密协议（NDA）,为客户提供一个安全可靠的环境。",
            "text-6":"近年来，在商业模式变革和新业务创设中,数据的收集、存储和利用变得尤为重要。数据收集关注如何获取客户数据和物联网（IoT）数据,存储则涉及如何高效加工、处理和保存原始数据,而数据利用的关键在于如何通过机器学习和BI工具进行分析。因此,商业模式变革和新业务创设正与数字化转型（DX）密不可分。在企业解决方案业务中,我们为流通、金融、服务、制造、互联网、社会基础设施、教育、学术、医疗和公共机构等各行业客户提供咨询、开发、系统构建和支持服务,同时也擅长利用技术进行制造创新。我们始终坚持以客户需求为核心，致力于提供最佳解决方案，凭借完善的体系，从咨询、开发、系统构建到支持，提供全面的一站式解决方案，满足各行业的多样化需求",
            "text-7":"我们的业务解决方案部门为流通、金融、服务、制造、互联网业务、社会基础设施、教育、学术、医疗和公共机构等各类客户提供咨询、开发、系统构建和支持服务，同时也擅长利用技术进行制造创新。我们始终致力于深入探索“客户的最佳选择是什么”，满足流通、金融、服务、制造、互联网业务、社会基础设施、教育、学术、医疗和公共机构等各行业的多样化需求。凭借完善的体系，我们提供从咨询、开发、系统构建到支持的全方位解决方案。",
            "text-8":"设计和开发的效率化，以及生产力提升是制造业中备受关注的主题。在这个主题下,DX（数字化转型）的目标是让非熟练者也能够做那些熟练者无需意识到的事情。此外,随着这一进程的推进,已经能够由任何人完成的工作也可以考虑由AI来替代。",
            "text-9": "在人力资源培养/教育领域,推动DX（数字化转型）以增强企业竞争力的需求也在增加。其主要目标是通过数据可视化提升人力资源管理的水平。通过对员工的海量数据（如技能、特征、经历等）进行集中管理,如果能够实现高精度的适岗人员配置，将为企业管理和员工的动机提供有效的人才管理。",
            "text-10": "在制造业中,数字化转型（DX）在工程链（开发 - 产品设计 - 工艺设计 - 生产等环节）和供应链（订单接收与发货 - 生产管理 - 生产 - 分销与销售 - 售后服务等环节）中得到广泛推进。 ",
            "text-11": "在医疗和护理行业,医疗人员短缺问题日益严重。这主要由不规律的工作环境、繁重的责任以及由于人口老龄化导致的需求增加等因素引起。数字化转型（DX）作为解决这些医疗和护理行业问题的手段，受到了广泛关注。具体来说，涉及到医疗设备的高端化、医疗信息的网络化、远程诊疗和利用物联网（IoT）进行监护等。日本政府还制定了“医疗DX令和愿景2030”,旨在通过改变社会和生活的形式，让国民能够享受更优质的医疗和护理服务。",
            "text-12": "在日本，为了吸引更多的入境需求并成为旅游强国，旅游行业的数字化转型（DX）也在推进。日本国土交通省提出通过构建可以进行预订和支付的地方网站、推荐信息、引入客户预订管理系统（PMS）等措施，提升业务效率和服务附加值，并通过使用旅行者的旅行前、旅行中、旅行后的预订、移动、住宿、购买数据等进行市场营销以及制定旅游地经营战略等,推进数字化转型的各项工作。",
            "text-13": "教育行业的数字化转型（DX）也在文部科学省的主导下推进。通过DX，预期的变化包括利用学习数据个性化教学、通过远程授课等方式建立不受地点限制的学习环境、减少教师的行政工作等。另一方面，在没有信息系统部门等IT部门的教育现场，DX推动方面的知识和经验不足往往成为问题，如何有效利用外部资源成为一大挑战。",
            "text-14":"零售行业面临着系统老化、长期的人才短缺以及缺乏做出经营决策所需的数据等问题，数字化转型（DX）作为解决这些问题的手段受到了关注。针对系统老化，考虑采用云化和引入最新系统；针对人才短缺，考虑引入人工智能（AI）和机器人过程自动化（RPA）；针对数据短缺，考虑通过电子商务（EC）进行数据收集。",
        },
        korean: {
            "text-1": "우리는 개발부터 도입까지 일관된 지원을 제공하는 원스톱 솔루션을 제공합니다. 고객님의 고민과 요구사항을 충분히 듣고, 이를 바탕으로 최적의 제안을 드립니다. 시스템 도입을 처음 고려하시고 어디서부터 시작해야 할지 모르겠다 고 고민하시는 분들도, 풍부한 실적을 가진 직원들이 도입 프로세스를 확실히 지원하므로 안심하고 진행하실 수 있습니다.",
            "paragraph1":"고객의 비즈니스 니즈와 업무 과제를 깊이 이해하고, 업무에 최적화된 맞춤형 소프트웨어 개발을 제공합니다. 고객의 업종과 비즈니스 규모에 맞춰 최적의 솔루션을 설계하고 개발하며, 업무 효율화 및 프로세스 자동화를 지원합니다. 이를 통해 업무 낭비를 줄이고, 작업 시간을 단축시키며, 휴먼 에러를 감소시켜 효율적인 운영을 실현합니다.",
            "paragraph2":"저희는 단순히 시스템을 제공하는 것에 그치지 않고, 고객의 성장을 돕기 위해 장기적인 파트너로서 지원합니다. 끊임없이 변화하는 시장 환경과 고객의 니즈에 유연하게 대응하며, 발전하는 비즈니스 요구 사항에 최적화된 기술을 지속적으로 제공합니다.",
            "text-2":"우리는 기업과 브랜드의 매력을 최대한 이끌어내기 위해 홈페이지와 광고의 설계 및 제작을 담당하고 있습니다. 디자인성과 기능성을巧妙히 융합하여 시각적 임팩트와 우수한 사용자 경험을 제공합니다. 우리의 창의적인 제안은 단순한 디지털 디자인에 그치지 않고, 브랜드 메시지를 생동감 있게 전달하는 강력한 표현이 되어 사용자들의 마음을 사로잡습니다. 최첨단 기술과 독창적인 시각으로 기업 성장에 가속을 붙이는 디지털 경험을 창출합니다. 당신의 브랜드를 다음 단계로 이끄는 유일무이한 파트너가 될 것입니다.",
            "paragraph3":"우리는 고객의 문제를 철저히 이해하고, 업무 효율화와 생산성 향상을 실현하는 업무 대행 서비스를 제공합니다. 경험이 풍부한 전문 직원과 유연한 체제로 모든 업무에 대응합니다. 기업 성장의 가속화를 위해 단순한 지원을 넘어서, 귀사의 전략적 파트너로서 신뢰를 얻고 있습니다. 효율화를 넘어서는 혁신적인 접근법으로 업무 부담을 줄이고, 최전선에서 활약할 수 있는 체제를 구축합니다. 이를 통해 기업이 가진 잠재력을 최대한 발휘하고, 지속 가능한 성장을 지원합니다. 우리와 함께 미래의 비즈니스 환경에서 성공할 수 있는 강력한 기반을 구축합시다.",
            "text-3":"당사는 사무 대행 업무의 일환으로 업무 흐름과 매뉴얼 작성을 진행합니다. 이를 통해 서비스 이용 중뿐만 아니라 서비스 종료 후에도 고객님이 원활하게 업무를 인수할 수 있는 체계를 구축합니다. 또한 정기적인 노하우 공유와 필요한 경우 교육 지원을 실시하여 사내에서 스킬을 축적할 수 있도록 돕습니다.",
            "text-4":"일일 업무 보고서 외에도 주간 및 월간 정기 보고 회의를 통해 업무 내용을 상세히 보고합니다. 이 과정을 통해 업무의 가시화를 실현하고, 고객이 효율성을 항상 확인할 수 있도록 합니다. 또한, 히어링을 통해 고객의 요구사항을 반영하여 최적의 서비스를 제공하는 데 최선을 다하고 있습니다.",
            "text-5":"당사는 개인정보보호 마크 및 ISMS(정보보호 관리체계) 인증을 보유하고 있으며, 정보 관리 체계의 신뢰성을 보장합니다. 또한, 업무를 수행하는 시설은 최신 보안 대책을 도입하여 기밀 정보 보호에 만전을 기하고 있습니다. 계약 시에는 비밀유지계약(NDA)을 체결하여 안전하고 신뢰할 수 있는 환경을 제공합니다.",
            "text-6":"최근 비즈니스 모델 혁신과 신규 사업 창출에 있어 데이터의 수집, 축적 및 활용이 중요해지고 있습니다. '수집'에서는 고객 데이터와 IoT 데이터를 어떻게 모을 것인가, '축적'에서는 원본 데이터를 어떻게 가공·처리·보관하여 활용하기 쉽게 만들 것인가, '활용'에서는 머신러닝과 BI 도구를 사용하여 어떻게 분석할 것인가가 핵심 포인트입니다. 따라서, 비즈니스 모델 혁신과 신규 사업 창출은 디지털 트랜스포메이션(DX)과 떼려야 뗄 수 없는 관계가 되어가고 있습니다.업무 솔루션 사업에서는 유통, 금융, 서비스, 제조, 인터넷 비즈니스, 사회 인프라, 교육, 학술, 의료, 공공 기관 등 다양한 고객을 대상으로 컨설팅, 개발, 시스템 구축, 지원을 제공하며, 기술을 활용한 제조 역량도 갖춘 기업입니다.우리는 유통, 금융, 서비스, 제조, 인터넷 비즈니스, 사회 인프라, 교육, 학술, 의료, 공공 기관 등 다양한 산업의 요구에 맞춰 '고객에게 최선의 선택은 무엇인가'를 철저히 고민하며, 컨설팅부터 개발, 시스템 구축, 지원까지 종합적인 솔루션을 제공합니다.",
            "text-7":"당사의 업무 솔루션 사업은 유통, 금융, 서비스, 제조, 온라인 비즈니스, 사회 인프라, 교육, 학술, 의료, 공공 기관 등 다양한 고객에게 컨설팅, 개발, 시스템 구축 및 지원 서비스를 제공하며, 기술을 활용한 제조 역량 또한 보유하고 있습니다.우리는 유통, 금융, 서비스, 제조, 온라인 비즈니스, 사회 인프라, 교육, 학술, 의료, 공공 기관 등 다양한 산업의 요구를 충족시키기 위해 '고객에게 최선의 선택은 무엇인가'를 철저히 고민하며, 컨설팅, 개발, 시스템 구축부터 지원까지 전반적인 솔루션을 제공합니다.","text-8":"",
            "text-8":"설계 및 개발의 효율화, 생산성 향상은 제조업을 중심으로 관심을 끌고 있는 주제입니다. 이 주제에서 DX(디지털 전환)의 목표는 숙련자가 무의식적으로 할 수 있는 일을 비숙련자도 할 수 있도록 만드는 것입니다. 또한 그 이후에는 누구나 할 수 있게 된 업무는 AI로 대체할 수 있다는 점을 염두에 두는 것도 가능합니다.",
            "text-9": "인재 육성/교육 분야에서도 기업 경쟁력 강화를 위한 DX(디지털 전환) 추진이 요구되고 있습니다. 그 주요 목표는 데이터 가시화를 통한 인재 관리의 고도화입니다. 직원에 관한 방대한 데이터(스킬, 특성, 경력 등)를 중앙 집중 관리함으로써 정확한 적재적소 인력 배치가 가능하다면, 기업 경영과 직원의 동기 부여 모두에 효과적인 인재 관리가 실현될 수 있습니다.",
            "text-10": "제조업에서는 엔지니어링 체인(개발 - 제품 설계 - 공정 설계 - 생산 등)의 연쇄와 공급망(주문 접수 - 생산 관리 - 생산 - 유통 및 판매 - 애프터 서비스 등)의 연쇄에서 디지털 전환(DX)이 폭넓게 추진되고 있습니다.",
            "text-11": "의료 / 요양 산업에서는 의료 종사자 부족이 심각해지고 있습니다. 불규칙한 근무 환경이나 중대한 책임 등으로 인한 인력 부족과 고령화의 진행으로 인한 수요 확대가 주요 원인입니다. DX(디지털 전환)는 이러한 의료 / 요양 산업의 문제 해결 수단으로 주목받고 있습니다. 구체적으로는 의료 기기의 고도화, 의료 정보의 네트워크화, 원격 진료, IoT를 활용한 모니터링 등이 있습니다. 일본 정부는 '의료 DX 레이와 비전 2030'을 제정하여, 국민이 더 나은 의료와 요양을 받을 수 있는 사회와 생활의 형태를 변화시키는 것을 목표로 하고 있습니다.",
            "text-12": "일본은 더 많은 인바운드 수요를 유치하고 관광 강국을 목표로 관광 산업의 디지털 전환(DX)을 추진하고 있습니다. 일본 국토교통성은 예약 및 결제가 가능한 지역 사이트 구축, 정보 추천, 고객 예약 관리 시스템(PMS) 도입 등을 통해 업무 효율화와 서비스의 부가가치 향상을 이루고, 여행자의 여행 전, 여행 중, 여행 후의 예약, 이동, 숙박, 구매 데이터 등을 활용한 마케팅 및 관광지 경영 전략 수립 등을 DX로 추진하고 있습니다.",
            "text-13": "교육 산업의 디지털 전환(DX)은 문부과학성 주도로 추진되고 있습니다. DX로 인해 기대되는 변화로는 학습 데이터를 활용한 개별화된 지도, 원격 수업 등을 통한 장소에 구애받지 않는 학습 환경 구축, 교사의 행정 업무 경감 등이 있습니다. 한편, 정보 시스템 부서 등 IT 관련 부서가 없는 교육 현장에서는 DX 추진에 대한 지식 부족과 경험 부족이 문제로 대두될 수 있으며, 외부 리소스를 어떻게 활용할 것인지가 주요 과제로 떠오르고 있습니다.",
            "text-14":"소매업계는 시스템 노후화, 만성적인 인력 부족, 경영 판단에 필요한 데이터 부족 등 여러 과제에 직면해 있으며, 이러한 문제 해결 수단으로 디지털 전환(DX)이 주목받고 있습니다. 시스템 노후화에 대해서는 클라우드화 및 최신 시스템 도입, 인력 부족에 대해서는 AI와 RPA 도입, 데이터 부족에 대해서는 전자상거래(EC)를 통한 데이터 수집 등이 고려되고 있습니다.",
        }
    };

    const langTexts = text[language];

    for (const id in langTexts) {
        document.getElementById(id).innerHTML = langTexts[id];
    }
}